/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardDocumentRouteRouteImport } from './routes/dashboard/document/route'
import { Route as DashboardKeyIndexRouteImport } from './routes/dashboard/key/index'
import { Route as DashboardDocumentIndexRouteImport } from './routes/dashboard/document/index'
import { Route as DashboardKeyCreateRouteImport } from './routes/dashboard/key/create'
import { Route as DashboardDocumentUploadRouteImport } from './routes/dashboard/document/upload'
import { Route as DashboardDocumentSignRouteImport } from './routes/dashboard/document/sign'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardDocumentRouteRoute = DashboardDocumentRouteRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKeyIndexRoute = DashboardKeyIndexRouteImport.update({
  id: '/key/',
  path: '/key/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentIndexRoute = DashboardDocumentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDocumentRouteRoute,
} as any)
const DashboardKeyCreateRoute = DashboardKeyCreateRouteImport.update({
  id: '/key/create',
  path: '/key/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentUploadRoute = DashboardDocumentUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardDocumentRouteRoute,
} as any)
const DashboardDocumentSignRoute = DashboardDocumentSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => DashboardDocumentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/document': typeof DashboardDocumentRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/document/sign': typeof DashboardDocumentSignRoute
  '/dashboard/document/upload': typeof DashboardDocumentUploadRoute
  '/dashboard/key/create': typeof DashboardKeyCreateRoute
  '/dashboard/document/': typeof DashboardDocumentIndexRoute
  '/dashboard/key/': typeof DashboardKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/document/sign': typeof DashboardDocumentSignRoute
  '/dashboard/document/upload': typeof DashboardDocumentUploadRoute
  '/dashboard/key/create': typeof DashboardKeyCreateRoute
  '/dashboard/document': typeof DashboardDocumentIndexRoute
  '/dashboard/key': typeof DashboardKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard/document': typeof DashboardDocumentRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/dashboard/document/sign': typeof DashboardDocumentSignRoute
  '/dashboard/document/upload': typeof DashboardDocumentUploadRoute
  '/dashboard/key/create': typeof DashboardKeyCreateRoute
  '/dashboard/document/': typeof DashboardDocumentIndexRoute
  '/dashboard/key/': typeof DashboardKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/document'
    | '/login'
    | '/register'
    | '/dashboard/document/sign'
    | '/dashboard/document/upload'
    | '/dashboard/key/create'
    | '/dashboard/document/'
    | '/dashboard/key/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/document/sign'
    | '/dashboard/document/upload'
    | '/dashboard/key/create'
    | '/dashboard/document'
    | '/dashboard/key'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_auth'
    | '/dashboard/document'
    | '/_auth/login'
    | '/_auth/register'
    | '/dashboard/document/sign'
    | '/dashboard/document/upload'
    | '/dashboard/key/create'
    | '/dashboard/document/'
    | '/dashboard/key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/document': {
      id: '/dashboard/document'
      path: '/document'
      fullPath: '/dashboard/document'
      preLoaderRoute: typeof DashboardDocumentRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/key/': {
      id: '/dashboard/key/'
      path: '/key'
      fullPath: '/dashboard/key/'
      preLoaderRoute: typeof DashboardKeyIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/document/': {
      id: '/dashboard/document/'
      path: '/'
      fullPath: '/dashboard/document/'
      preLoaderRoute: typeof DashboardDocumentIndexRouteImport
      parentRoute: typeof DashboardDocumentRouteRoute
    }
    '/dashboard/key/create': {
      id: '/dashboard/key/create'
      path: '/key/create'
      fullPath: '/dashboard/key/create'
      preLoaderRoute: typeof DashboardKeyCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/document/upload': {
      id: '/dashboard/document/upload'
      path: '/upload'
      fullPath: '/dashboard/document/upload'
      preLoaderRoute: typeof DashboardDocumentUploadRouteImport
      parentRoute: typeof DashboardDocumentRouteRoute
    }
    '/dashboard/document/sign': {
      id: '/dashboard/document/sign'
      path: '/sign'
      fullPath: '/dashboard/document/sign'
      preLoaderRoute: typeof DashboardDocumentSignRouteImport
      parentRoute: typeof DashboardDocumentRouteRoute
    }
  }
}

interface DashboardDocumentRouteRouteChildren {
  DashboardDocumentSignRoute: typeof DashboardDocumentSignRoute
  DashboardDocumentUploadRoute: typeof DashboardDocumentUploadRoute
  DashboardDocumentIndexRoute: typeof DashboardDocumentIndexRoute
}

const DashboardDocumentRouteRouteChildren: DashboardDocumentRouteRouteChildren =
  {
    DashboardDocumentSignRoute: DashboardDocumentSignRoute,
    DashboardDocumentUploadRoute: DashboardDocumentUploadRoute,
    DashboardDocumentIndexRoute: DashboardDocumentIndexRoute,
  }

const DashboardDocumentRouteRouteWithChildren =
  DashboardDocumentRouteRoute._addFileChildren(
    DashboardDocumentRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardDocumentRouteRoute: typeof DashboardDocumentRouteRouteWithChildren
  DashboardKeyCreateRoute: typeof DashboardKeyCreateRoute
  DashboardKeyIndexRoute: typeof DashboardKeyIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDocumentRouteRoute: DashboardDocumentRouteRouteWithChildren,
  DashboardKeyCreateRoute: DashboardKeyCreateRoute,
  DashboardKeyIndexRoute: DashboardKeyIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
