/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as appVerifyRouteImport } from './routes/(app)/verify'
import { Route as DashboardKeyIndexRouteImport } from './routes/dashboard/key/index'
import { Route as DashboardDocumentIndexRouteImport } from './routes/dashboard/document/index'
import { Route as DashboardKeyCreateRouteImport } from './routes/dashboard/key/create'
import { Route as DashboardDocumentUploadRouteImport } from './routes/dashboard/document/upload'
import { Route as DashboardDocumentSignRouteImport } from './routes/dashboard/document/sign'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const appVerifyRoute = appVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => appRouteRoute,
} as any)
const DashboardKeyIndexRoute = DashboardKeyIndexRouteImport.update({
  id: '/key/',
  path: '/key/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentIndexRoute = DashboardDocumentIndexRouteImport.update({
  id: '/document/',
  path: '/document/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKeyCreateRoute = DashboardKeyCreateRouteImport.update({
  id: '/key/create',
  path: '/key/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentUploadRoute = DashboardDocumentUploadRouteImport.update({
  id: '/document/upload',
  path: '/document/upload',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentSignRoute = DashboardDocumentSignRouteImport.update({
  id: '/document/sign',
  path: '/document/sign',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof appIndexRoute
  '/verify': typeof appVerifyRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/document/sign': typeof DashboardDocumentSignRoute
  '/dashboard/document/upload': typeof DashboardDocumentUploadRoute
  '/dashboard/key/create': typeof DashboardKeyCreateRoute
  '/dashboard/document/': typeof DashboardDocumentIndexRoute
  '/dashboard/key/': typeof DashboardKeyIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof appIndexRoute
  '/verify': typeof appVerifyRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/document/sign': typeof DashboardDocumentSignRoute
  '/dashboard/document/upload': typeof DashboardDocumentUploadRoute
  '/dashboard/key/create': typeof DashboardKeyCreateRoute
  '/dashboard/document': typeof DashboardDocumentIndexRoute
  '/dashboard/key': typeof DashboardKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/(app)/verify': typeof appVerifyRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/(app)/': typeof appIndexRoute
  '/dashboard/document/sign': typeof DashboardDocumentSignRoute
  '/dashboard/document/upload': typeof DashboardDocumentUploadRoute
  '/dashboard/key/create': typeof DashboardKeyCreateRoute
  '/dashboard/document/': typeof DashboardDocumentIndexRoute
  '/dashboard/key/': typeof DashboardKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/verify'
    | '/login'
    | '/register'
    | '/dashboard/document/sign'
    | '/dashboard/document/upload'
    | '/dashboard/key/create'
    | '/dashboard/document/'
    | '/dashboard/key/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/'
    | '/verify'
    | '/login'
    | '/register'
    | '/dashboard/document/sign'
    | '/dashboard/document/upload'
    | '/dashboard/key/create'
    | '/dashboard/document'
    | '/dashboard/key'
  id:
    | '__root__'
    | '/(app)'
    | '/dashboard'
    | '/_auth'
    | '/(app)/verify'
    | '/_auth/login'
    | '/_auth/register'
    | '/(app)/'
    | '/dashboard/document/sign'
    | '/dashboard/document/upload'
    | '/dashboard/key/create'
    | '/dashboard/document/'
    | '/dashboard/key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(app)/verify': {
      id: '/(app)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof appVerifyRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/dashboard/key/': {
      id: '/dashboard/key/'
      path: '/key'
      fullPath: '/dashboard/key/'
      preLoaderRoute: typeof DashboardKeyIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/document/': {
      id: '/dashboard/document/'
      path: '/document'
      fullPath: '/dashboard/document/'
      preLoaderRoute: typeof DashboardDocumentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/key/create': {
      id: '/dashboard/key/create'
      path: '/key/create'
      fullPath: '/dashboard/key/create'
      preLoaderRoute: typeof DashboardKeyCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/document/upload': {
      id: '/dashboard/document/upload'
      path: '/document/upload'
      fullPath: '/dashboard/document/upload'
      preLoaderRoute: typeof DashboardDocumentUploadRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/document/sign': {
      id: '/dashboard/document/sign'
      path: '/document/sign'
      fullPath: '/dashboard/document/sign'
      preLoaderRoute: typeof DashboardDocumentSignRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appVerifyRoute: typeof appVerifyRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appVerifyRoute: appVerifyRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDocumentSignRoute: typeof DashboardDocumentSignRoute
  DashboardDocumentUploadRoute: typeof DashboardDocumentUploadRoute
  DashboardKeyCreateRoute: typeof DashboardKeyCreateRoute
  DashboardDocumentIndexRoute: typeof DashboardDocumentIndexRoute
  DashboardKeyIndexRoute: typeof DashboardKeyIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDocumentSignRoute: DashboardDocumentSignRoute,
  DashboardDocumentUploadRoute: DashboardDocumentUploadRoute,
  DashboardKeyCreateRoute: DashboardKeyCreateRoute,
  DashboardDocumentIndexRoute: DashboardDocumentIndexRoute,
  DashboardKeyIndexRoute: DashboardKeyIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
